---
- name: Install make
  become: yes
  become_method: sudo
  apt: name=make state=present

- name: Install GCC
  become: yes
  become_method: sudo
  apt: name=gcc state=present


- command: make hiredis lua jemalloc linenoise
  args:
    chdir: ~/redis/deps

- name: Install build-essential
  become: yes
  become_method: sudo
  apt: name=build-essential state=present

- command: make
  args:
    chdir: ~/redis

- name: Source profile
  shell: source /etc/profile
  args:
    executable: /bin/bash

- name: add pass to redis.conf
  shell: echo "requirepass password" >> ~/redis/redis.conf

- shell: nohup redis-server ./redis.conf &
  args:
    chdir: ~/redis

  
  