- hosts: web
  user: ubuntu
  vars_files:
    - vars/main.yml 
  roles:
  # - updateNode
  # - downloadInstallPackages
  # - Cassandra
<<<<<<< HEAD
  - Redis
  - Kafka
  - Gradle
  - Nodejs
  - apiGateway
  - UI
  - Microservice
=======
  # - Redis
  - Kafka
>>>>>>> 9ae3f5f50aa1d82c1aa2c33b60b86da7dca93357
