- hosts: web
  user: sree
  # vars_files:
  #   - vars/main.yml 
  roles:
  - updateNode
  - downloadInstallPackages
  - Cassandra
  - Redis
  - Kafka
  - Nodejs
  - apiGateway
  - UI
  - Gradle
  # - Microservice  
  

