- hosts: web
  remote_user: root
  become: yes
  vars_files:
    - vars/main.yml 
  roles:
  - updateNode
  - futurice.cassandra
  - sbaerlocher.redis
  - weldpua2008.openjdk
  - stevenharradine.apache2
  - geerlingguy.nodejs
  # - setupSchema
  - zookeeper
  - kafka
t