- hosts: web
  user: cisco
  vars_files:
    - vars/main.yml 
  roles:
  - updateNode
  - downloadInstallPackages
  - Cassandra
  - Redis
  - Kafka
  - Gradle
  - Nodejs
  - apiGateway
  - UI
  # - Microservice

