---

- name: Run gradle
  command: gradle 
  args:
    chdir: /home/cisco/
  
- name: Source ccsrc
  shell: source ccsrc
  args:
    chdir: ~/skyfall
    executable: /bin/bash


- name: Building Microservices
  command: gradle -x test microservice:administration:build 
  args:
    chdir: ~/skyfall/server 
    # executable: /bin/bash.... comment this and it works
- name: Building Microservices
  command: gradle -x test microservice:idm:build 
  args:
    chdir: ~/skyfall/server 
    #executable: /bin/bash
- name: Building Microservices
  command: gradle -x test microservice:orchestration:build 
  args:
    chdir: ~/skyfall/server 
    #executable: /bin/bash
- name: Building Microservices
  command: gradle -x test microservice:consume:build 
  args:
    chdir: ~/skyfall/server 
    #executable: /bin/bash
- name: Building Microservices
  command: gradle -x test microservice:manage:build 
  args:
    chdir: ~/skyfall/server 
    #executable: /bin/bash
- name: Building Microservices
  command: gradle -x test microservice:monitor:build 
  args:
    chdir: ~/skyfall/server 
    #executable: /bin/bash
- name: Building Microservices
  command: gradle -x test microservice:cgps:build 
  args:
    chdir: ~/skyfall/server 
    #executable: /bin/bash
- name: Building Microservices
  command: gradle -x test microservice:iwan:build 
  args:
    chdir: ~/skyfall/server 
    #executable: /bin/bash
- name: Building Microservices
  command: gradle -x test microservice:logconsumer:build 
  args:
    chdir: ~/skyfall/server 
    #executable: /bin/bash
- name: Building Microservices
  command: gradle -x test microservice:notification:build 
  args:
    chdir: ~/skyfall/server 
    #executable: /bin/bash
  
- name: Running DB Installer
  command: java -jar administration/build/libs/administration-1.0.0.BUILD-SNAPSHOT.jar -Mode NewInstall 
  args:
    chdir: ~/skyfall/server/microservice 
    # executable: /bin/bash
- name: Running DB Installer
  command: java -jar idm/build/libs/idm-1.0.0.BUILD-SNAPSHOT.jar -Mode NewInstall 
  args:
    chdir: ~/skyfall/server/microservice 
- name: Running DB Installer
  command: java -jar orchestration/build/libs/orchestration-2.3.0-SNAPSHOT.jar -Mode NewInstall 
  args:
    chdir: ~/skyfall/server/microservice 
- name: Running DB Installer
  command: java -jar consume/build/libs/consume-1.0.0.BUILD-SNAPSHOT.jar -Mode NewInstall 
  args:
    chdir: ~/skyfall/server/microservice 
- name: Running DB Installer
  command: java -jar manage/build/libs/manage-1.0.0.BUILD-SNAPSHOT.jar -Mode NewInstall 
  args:
    chdir: ~/skyfall/server/microservice 
- name: Running DB Installer
  command: java -jar monitor/build/libs/monitor-1.0.0.BUILD-SNAPSHOT.jar -Mode NewInstall 
  args:
    chdir: ~/skyfall/server/microservice 
- name: Running DB Installer
  command: java -jar cgps/build/libs/cgps-1.0.0.BUILD-SNAPSHOT.jar -Mode NewInstall 
  args:
    chdir: ~/skyfall/server/microservice 
- name: Running DB Installer
  command: java -jar iwan/build/libs/iwan-1.0.0.BUILD-SNAPSHOT.jar -Mode NewInstall 
  args:
    chdir: ~/skyfall/server/microservice 
- name: Running DB Installer
  command: java -jar logconsumer/build/libs/logconsumer-1.0.0.BUILD-SNAPSHOT.jar -Mode NewInstall 
  args:
    chdir: ~/skyfall/server/microservice 
- name: Running DB Installer
  command: java -jar notification/build/libs/notification-1.0.0.BUILD-SNAPSHOT.jar -Mode NewInstall 
  args:
    chdir: ~/skyfall/server/microservice 