---

- name: Source /etc/profile
  shell: source /etc/profile
  args:
    executable: /bin/bash

- name: Source /etc/environment
  shell: source /etc/environment
  args:
    executable: /bin/bash

- name: Run gradle
  command: gradle 
  args:
    chdir: ~/gradle
  
- name: Source ccsrc
  shell: source ccsrc
  args:
    chdir: ~/skyfall
    executable: /bin/bash


- name: Building Microservices 1
  command: gradle -x test microservice:administration:build 
  args:
    chdir: ~/skyfall/server

- name: Running DB Installer 1
  shell: source ~/skyfall/ccsrc && java -jar ~/skyfall/server/microservice/administration/build/libs/administration-2.3.0.BUILD-SNAPSHOT.jar -Mode NewInstall
  args:
    executable: /bin/bash

- name: Running Microservices 1
  shell: source ~/skyfall/ccsrc && nohup java -jar ~/skyfall/server/microservice/administration/build/libs/administration-2.3.0.BUILD-SNAPSHOT.jar &
  args:
    executable: /bin/bash


    
- name: Building Microservices 2
  command: gradle -x test microservice:idm:build 
  args:
    chdir: ~/skyfall/server 

- name: Running DB Installer 2
  shell: source ~/skyfall/ccsrc && java -jar ~/skyfall/server/microservice/idm/build/libs/idm-2.3.0.BUILD-SNAPSHOT.jar -Mode NewInstall
  args:
    executable: /bin/bash

- name: Running Microservices 2
  shell: source ~/skyfall/ccsrc && nohup java -jar ~/skyfall/server/microservice/idm/build/libs/idm-2.3.0.BUILD-SNAPSHOT.jar &
  args:
    executable: /bin/bash
    


- name: Building Microservices 3
  command: gradle -x test microservice:orchestration:build 
  args:
    chdir: ~/skyfall/server 

- name: Running DB Installer 3
  shell: source ~/skyfall/ccsrc && java -jar ~/skyfall/server/microservice/orchestration/build/libs/orchestration-2.3.0.BUILD-SNAPSHOT.jar -Mode NewInstall
  args:
    executable: /bin/bash

- name: Running Microservices 3
  shell: source ~/skyfall/ccsrc && nohup java -jar ~/skyfall/server/microservice/orchestration/build/libs/orchestration-2.3.0.BUILD-SNAPSHOT.jar &
  args:
    executable: /bin/bash



    
- name: Building Microservices 4
  command: gradle -x test microservice:consume:build 
  args:
    chdir: ~/skyfall/server 
    
- name: Running DB Installer 4
  shell: source ~/skyfall/ccsrc && java -jar ~/skyfall/server/microservice/consume/build/libs/consume-2.3.0.BUILD-SNAPSHOT.jar -Mode NewInstall
  args:
    executable: /bin/bash

- name: Running Microservices 4
  shell: source ~/skyfall/ccsrc && nohup java -jar ~/skyfall/server/microservice/consume/build/libs/consume-2.3.0.BUILD-SNAPSHOT.jar &
  args:
    executable: /bin/bash



- name: Building Microservices 5
  command: gradle -x test microservice:manage:build 
  args:
    chdir: ~/skyfall/server 

- name: Running DB Installer 5
  shell: source ~/skyfall/ccsrc && java -jar ~/skyfall/server/microservice/manage/build/libs/manage-2.3.0.BUILD-SNAPSHOT.jar -Mode NewInstall
  args:
    executable: /bin/bash

- name: Running Microservices 5
  shell: source ~/skyfall/ccsrc && nohup java -jar ~/skyfall/server/microservice/manage/build/libs/manage-2.3.0.BUILD-SNAPSHOT.jar &
  args:
    executable: /bin/bash
  


- name: Building Microservices 6
  command: gradle -x test microservice:monitor:build 
  args:
    chdir: ~/skyfall/server 
    
- name: Running DB Installer 6
  shell: source ~/skyfall/ccsrc && java -jar ~/skyfall/server/microservice/monitor/build/libs/monitor-2.3.0.BUILD-SNAPSHOT.jar -Mode NewInstall
  args:
    executable: /bin/bash

- name: Running Microservices 6
  shell: source ~/skyfall/ccsrc && nohup java -jar ~/skyfall/server/microservice/monitor/build/libs/monitor-2.3.0.BUILD-SNAPSHOT.jar &
  args:
    executable: /bin/bash



- name: Building Microservices 7
  command: gradle -x test microservice:cgps:build 
  args:
    chdir: ~/skyfall/server 
    
- name: Running DB Installer 7
  shell: source ~/skyfall/ccsrc && java -jar ~/skyfall/server/microservice/cgps/build/libs/cgps-2.3.0.BUILD-SNAPSHOT.jar -Mode NewInstall
  args:
    executable: /bin/bash



- name: Building Microservices 8
  command: gradle -x test microservice:iwan:build 
  args:
    chdir: ~/skyfall/server 

- name: Running DB Installer 8
  shell: source ~/skyfall/ccsrc && java -jar ~/skyfall/server/microservice/iwan/build/libs/iwan-2.3.0.BUILD-SNAPSHOT.jar -Mode NewInstall
  args:
    executable: /bin/bash

- name: Running Microservices 8
  shell: source ~/skyfall/ccsrc && nohup java -jar ~/skyfall/server/microservice/iwan/build/libs/iwan-2.3.0.BUILD-SNAPSHOT.jar &
  args:
    executable: /bin/bash

    
- name: Building Microservices 9
  command: gradle -x test microservice:logconsumer:build 
  args:
    chdir: ~/skyfall/server 
    
- name: Running DB Installer 9
  shell: source ~/skyfall/ccsrc && java -jar ~/skyfall/server/microservice/logconsumer/build/libs/logconsumer-2.3.0.BUILD-SNAPSHOT.jar -Mode NewInstall
  args:
    executable: /bin/bash

- name: Running Microservices 9
  shell: source ~/skyfall/ccsrc && nohup java -jar ~/skyfall/server/microservice/logconsumer/build/libs/logconsumer-2.3.0.BUILD-SNAPSHOT.jar &
  args:
    executable: /bin/bash


- name: Building Microservices 10
  command: gradle -x test microservice:notification:build 
  args:
    chdir: ~/skyfall/server 
    
- name: Running DB Installer 10
  shell: source ~/skyfall/ccsrc && java -jar ~/skyfall/server/microservice/notification/build/libs/notification-2.3.0.BUILD-SNAPSHOT.jar -Mode NewInstall
  args:
    executable: /bin/bash

- name: Running Microservices 10
  shell: source ~/skyfall/ccsrc && nohup java -jar ~/skyfall/server/microservice/server/microservice/notification/build/libs/notification-2.3.0.BUILD-SNAPSHOT.jar &
  args:
    executable: /bin/bash
