---
- name: Set environment variables for gradle
  environment:
    GRADLE_HOME: ~/gradle
    PATH: $PATH:$GRADLE_HOME/bin
  
- name: Run gradle
  command: gradle
  args:
    chdir: ~/gradle

- name: Source ccsrc
  command: source ccsrc
  args:
    chdir: ~/skyfall

- name: Building Microservices
  command: gradle -x test microservice:administration:build
  args:
    chdir: ~/skyfall/server 
  command: gradle -x test microservice:idm:build
  args:
    chdir: ~/skyfall/server 
  command: gradle -x test microservice:orchestration:build
  args:
    chdir: ~/skyfall/server 
  command: gradle -x test microservice:consume:build
  args:
    chdir: ~/skyfall/server 
  command: gradle -x test microservice:manage:build
  args:
    chdir: ~/skyfall/server 
  command: gradle -x test microservice:monitor:build
  args:
    chdir: ~/skyfall/server 
  command: gradle -x test microservice:cgps:build
  args:
    chdir: ~/skyfall/server 
  command: gradle -x test microservice:iwan:build
  args:
    chdir: ~/skyfall/server 
  command: gradle -x test microservice:logconsumer:build
  args:
    chdir: ~/skyfall/server 
  command: gradle -x test microservice:notification:build
  args:
    chdir: ~/skyfall/server 
  
- name: Running DB Installer
  command: java -jar administration/build/libs/*.jar -Mode NewInstall
  args:
    chdir: ~/skyfall/server/microservice 
  command: java -jar idm/build/libs/*.jar -Mode NewInstall
  args:
    chdir: ~/skyfall/server/microservice 
  command: java -jar orchestration/build/libs/*.jar -Mode NewInstall
  args:
    chdir: ~/skyfall/server/microservice 
  command: java -jar consume/build/libs/*.jar -Mode NewInstall
  args:
    chdir: ~/skyfall/server/microservice 
  command: java -jar manage/build/libs/*.jar -Mode NewInstall
  args:
    chdir: ~/skyfall/server/microservice 
  command: java -jar monitor/build/libs/*.jar -Mode NewInstall
  args:
    chdir: ~/skyfall/server/microservice 
  command: java -jar cgps/build/libs/*.jar -Mode NewInstall
  args:
    chdir: ~/skyfall/server/microservice 
  command: java -jar iwan/build/libs/*.jar -Mode NewInstall
  args:
    chdir: ~/skyfall/server/microservice 
  command: java -jar logconsumer/build/libs/*.jar -Mode NewInstall
  args:
    chdir: ~/skyfall/server/microservice 
  command: java -jar notification/build/libs/*.jar -Mode NewInstall
  args:
    chdir: ~/skyfall/server/microservice 
  