---
- name: Create directory cassandra
  sudo: True
  file: state=directory path=/var/lib/cassandra owner=ubuntu group=ubuntu

- name: Create directory cassandra
  file: path=/var/log/cassandra state=directory owner=ubuntu group=ubuntu
  sudo: yes


  environment:
    CASSANDRA_HOME: ~/cassandra
    PATH: $PATH:$CASSANDRA_HOME/bin