---
- name: Create directory cassandra
  sudo: True
  file: state=directory path=/var/lib/cassandra owner={{owner}} group={{group}}

- name: Create directory cassandra
  sudo: True
  file: path=/var/log/cassandra state=directory owner={{owner}} group={{group}}
  


- name: Set Cassandra path to /etc/environment
  sudo: True
  lineinfile: dest=/etc/environment state=present backrefs=yes regexp='PATH=(["]*)((?!.*?{{path}}/cassandra/bin).*?)(["]*)$' line="PATH=\1\2:{{path}}/cassandra/bin\3"

- name: Set java path to /etc/environment
  sudo: True
  lineinfile: dest=/etc/environment state=present backrefs=yes regexp='PATH=(["]*)((?!.*?/usr/local/java/bin).*?)(["]*)$' line="PATH=\1\2:/usr/local/java/bin\3"

- name: Set jre path to /etc/environment
  sudo: True
  lineinfile: dest=/etc/environment state=present backrefs=yes regexp='PATH=(["]*)((?!.*?/usr/local/java/bin).*?)(["]*)$' line="PATH=\1\2:/usr/local/java/bin\3"

- name: add gradle path to /etc/environment
  sudo: True
  lineinfile: dest=/etc/environment state=present backrefs=yes regexp='PATH=(["]*)((?!.*?{{path}}/gradle/bin).*?)(["]*)$' line="PATH=\1\2:{{path}}/gradle/bin\3"

- name: add redis path to /etc/environment
  sudo: True
  lineinfile: dest=/etc/environment state=present backrefs=yes regexp='PATH=(["]*)((?!.*?{{path}}/redis/src).*?)(["]*)$' line="PATH=\1\2:{{path}}/redis/src\3"

- name: add kafka path to /etc/environment
  sudo: True
  lineinfile: dest=/etc/environment state=present backrefs=yes regexp='PATH=(["]*)((?!.*?{{path}}/kafka/bin).*?)(["]*)$' line="PATH=\1\2:{{path}}/kafka/bin\3"

- name: add bower path to /etc/environment
  sudo: True
  lineinfile: dest=/etc/environment state=present backrefs=yes regexp='PATH=(["]*)((?!.*?{{path}}/skyfall/ui/node_modules/bower/bin).*?)(["]*)$' line="PATH=\1\2:{{path}}/skyfall/ui/node_modules/bower/bin\3"

- name: Source /etc/environment
  shell: source /etc/environment
  args:
    executable: /bin/bash


- name: run Cassandra
  shell: source /etc/environment && nohup cassandra &
  args:
    chdir: ~/cassandra
    executable: /bin/bash
    



