---
- name: Create directory cassandra
  sudo: True
  file: state=directory path=/var/lib/cassandra owner=ubuntu group=ubuntu

- name: Create directory cassandra
  sudo: True
  file: path=/var/log/cassandra state=directory owner=ubuntu group=ubuntu

  environment:
    CASSANDRA_HOME: ~/cassandra
    PATH: $PATH:$CASSANDRA_HOME/bin

- shell: nohup cassandra &
  args:
    chdir: ~/cassandra/