---
- name: Create directory cassandra
  sudo: True
  file: state=directory path=/var/lib/cassandra owner=cisco group=cisco

- name: Create directory cassandra
  sudo: True
  file: path=/var/log/cassandra state=directory owner=cisco group=cisco
  


- name: Set Cassandra path to /etc/environment
  sudo: True
  lineinfile: dest=/etc/environment state=present backrefs=yes regexp='PATH=(["]*)((?!.*?/home/cisco/cassandra/bin).*?)(["]*)$' line="PATH=\1\2:/home/cisco/cassandra/bin\3"

- name: Set java path to /etc/environment
  sudo: True
  lineinfile: dest=/etc/environment state=present backrefs=yes regexp='PATH=(["]*)((?!.*?/usr/local/java/bin).*?)(["]*)$' line="PATH=\1\2:/usr/local/java/bin\3"

- name: Set jre path to /etc/environment
  sudo: True
  lineinfile: dest=/etc/environment state=present backrefs=yes regexp='PATH=(["]*)((?!.*?/usr/local/java/bin).*?)(["]*)$' line="PATH=\1\2:/usr/local/java/bin\3"

- name: add gradle path to /etc/environment
  sudo: True
  lineinfile: dest=/etc/environment state=present backrefs=yes regexp='PATH=(["]*)((?!.*?/home/cisco/gradle/bin).*?)(["]*)$' line="PATH=\1\2:/home/cisco/gradle/bin\3"

- name: add redis path to /etc/environment
  sudo: True
  lineinfile: dest=/etc/environment state=present backrefs=yes regexp='PATH=(["]*)((?!.*?/home/cisco/redis/src).*?)(["]*)$' line="PATH=\1\2:/home/cisco/redis/src\3"

- name: add kafka path to /etc/environment
  sudo: True
  lineinfile: dest=/etc/environment state=present backrefs=yes regexp='PATH=(["]*)((?!.*?/home/cisco/kafka/bin).*?)(["]*)$' line="PATH=\1\2:/home/cisco/kafka/bin\3"

- name: add bower path to /etc/environment
  sudo: True
  lineinfile: dest=/etc/environment state=present backrefs=yes regexp='PATH=(["]*)((?!.*?/home/cisco/skyfall/ui/node_modules/bower/bin).*?)(["]*)$' line="PATH=\1\2:/home/cisco/skyfall/ui/node_modules/bower/bin\3"

- name: run Cassandra
  shell: nohup cassandra &
  args:
    chdir: ~/cassandra
    executable: /bin/bash