---
galaxy_info:
  author: Jussi Vaihia
  description: Cassandra deployment
  company: Futurice
  license: BSD
  min_ansible_version: 1.9
  platforms:
  - name: Ubuntu
    versions:
    - trusty
  - name: Debian
    versions:
    - jessie
  categories:
    - web
dependencies: []
  
