---

galaxy_info:
  author: "Wojtek Oledzki"
  description: "Install Apache Zookeeper server."
  license: MIT
  min_ansible_version: 1.9
  platforms:
    - name: Ubuntu
      versions:
        - all
  categories:
    - development

dependencies: [ ]
