---

# - name: Running Microservices 1
#   shell: nohup java -jar administration/build/libs/administration-1.0.0.BUILD-SNAPSHOT.jar & 
#   args:
#     chdir: ~/skyfall/server/microservice 



# - name: Running Microservices 2
#   shell: nohup java -jar idm/build/libs/idm-1.0.0.BUILD-SNAPSHOT.jar &
#   args:
#     chdir: ~/skyfall/server/microservice 


- name: Source ccsrc
  shell: source ccsrc
  args:
    chdir: ~/skyfall
    executable: /bin/bash


- name: Running Microservices 3
  shell: nohup java -jar orchestration/build/libs/orchestration-1.0.0.BUILD-SNAPSHOT.jar &
  args:
    chdir: ~/skyfall/server/microservice 



- name: Source ccsrc
  shell: source ccsrc
  args:
    chdir: ~/skyfall
    executable: /bin/bash
    
- name: Running Microservices 4
  shell: nohup java -jar consume/build/libs/consume-1.0.0.BUILD-SNAPSHOT.jar &
  args:
    chdir: ~/skyfall/server/microservice 

- name: Source ccsrc
  shell: source ccsrc
  args:
    chdir: ~/skyfall
    executable: /bin/bash


- name: Running Microservices 5
  shell: nohup java -jar manage/build/libs/manage-1.0.0.BUILD-SNAPSHOT.jar &
  args:
    chdir: ~/skyfall/server/microservice 

- name: Source ccsrc
  shell: source ccsrc
  args:
    chdir: ~/skyfall
    executable: /bin/bash

- name: Running Microservices 6
  shell: nohup java -jar monitor/build/libs/monitor-1.0.0.BUILD-SNAPSHOT.jar &
  args:
    chdir: ~/skyfall/server/microservice 




# - name: Running Microservices 7
#   shell: nohup java -jar iwan/build/libs/iwan-1.0.0.BUILD-SNAPSHOT.jar &
#   args:
#     chdir: ~/skyfall/server/microservice 


- name: Source ccsrc
  shell: source ccsrc
  args:
    chdir: ~/skyfall
    executable: /bin/bash

- name: Running Microservices 8
  shell: nohup java -jar logconsumer/build/libs/logconsumer-1.0.0.BUILD-SNAPSHOT.jar &
  args:
    chdir: ~/skyfall/server/microservice 


- name: Source ccsrc
  shell: source ccsrc
  args:
    chdir: ~/skyfall
    executable: /bin/bash

- name: Running Microservices 9
  shell: nohup java -jar notification/build/libs/notification-1.0.0.BUILD-SNAPSHOT.jar &
  args:
    chdir: ~/skyfall/server/microservice 